### ISSUE TITLE
Not working. Doesn't show up in ModAPI.

### ISSUE THREAD

**Issue by x33st0rm** [john-dederer/Blueprints#2]
Title says it all.

**Comment by john-dederer** [comment]
With the new update isn't my mod deprecated?

**Comment by john-dederer** [comment]
I have uploaded a new version. Should work now.

**Comment by x33st0rm** [comment]
Wouldn't know anything about that.

I tried it, Save button works, but everything else, no... Can't say tho i'm quite certain what this mod does, never got it to show up i ModAPI before.
